package:
  name: iminuit
  version: 1.2

source:
  fn: iminuit-1.2.tar.gz
  url: https://pypi.python.org/packages/source/i/iminuit/iminuit-1.2.tar.gz#md5=4701ec472cae42015e26251703e6e984
  md5: 4701ec472cae42015e26251703e6e984

requirements:
  build:
    - cython
    - python
  run:
    - python

test:
  imports:
    - iminuit

about:
  license: MIT
  home: https://github.com/iminuit/iminuit
  summary: Numerical function minimization
