package:
  name: grainspotter
  version: "0.90"

source:
  svn_url: http://svn.code.sf.net/p/fable/code/GrainSpotter/trunk

  patches:
    - Makefile.patch # [linux]
    - mavericks.patch # [osx]
    - windows.patch # [win]

requirements:
  build:
    - mingw # [win]

#test:
#  commands:
#    - grainspotter

about:
  license: GPL
  home: https://sourceforge.net/projects/fable/
  summary: Fable program for spotting (indexing) grains by Søren Schmidt
