package:
  name: grainspotter
  version: trunk

source:
  svn_url: http://svn.code.sf.net/p/fable/code/GrainSpotter/trunk

  patches:
    - mavericks.patch

#test:
#  commands:
#    - grainspotter

about:
  license: LGPL
  home: https://sourceforge.net/projects/fable/
  summary: 3D x-ray diffraction utilities
