package:
  name: grainspotter
  version: trunk

source:
  svn_url: http://svn.code.sf.net/p/fable/code/GrainSpotter/trunk

  patches:
    - mavericks.patch # [osx]
    - windows.patch # [win]

#test:
#  commands:
#    - grainspotter

about:
  license: GPL
  home: https://sourceforge.net/projects/fable/
  summary: Fable program for spotting (indexing) grains by Søren Schmidt
