package:
  name: pillow
  version: "3.1.1"

source:
  git_url: https://github.com/python-pillow/Pillow.git
  git_rev: 3.1.1
  patches:
    - osx.patch # [osx]

requirements:
  build:
    - python
    - tk
    - zlib
    - libpng
    - libtiff
    - jpeg
    - freetype
    - distribute
  run:
    - python
    - tk
    - jpeg [unix]
    - zlib [unix]
    - freetype [unix]
    - libtiff [unix]

test:
  imports:
    - PIL
    - PIL.Image
    - PIL._imagingtk [linux]
    - PIL._imagingft [unix]

about:
  home: http://python-imaging.github.io/
  license: Standard PIL license
