package:
  name: polyxsim
  version: trunk

source:
  svn_url: http://svn.code.sf.net/p/fable/code/simulation/PolyXSim/trunk
  patches:

requirements:
  build:
    - python
  run:
    - fabio
    - numpy
    - pillow
    - python
    - scipy
    - xfab

test:
  imports:
    - polyxsim

about:
  license: GPL
  home: https://sourceforge.net/projects/fable/
  summary: Fable crystallography toolbox
