package:
  name: xfab
  version: trunk

source:
  svn_url: http://svn.code.sf.net/p/fable/code/xfab/trunk
  patches:

requirements:
  build:
    - python
  run:
    - imaged11
    - matplotlib
    - python
    - scipy

test:
  imports:
    - xfab
  commands:
    - findpeaks.py -h
    - flt_remove_beam.py -h
    - flt_split_phases.py -h
    - makemap_all.py -h
    - tweakdetpars.py -h

about:
  license: GPL
  home: https://sourceforge.net/projects/fable/
  summary: Fable crystallography toolbox
