package:
  name: xfab
  version: trunk

source:
  svn_url: http://svn.code.sf.net/p/fable/code/xfab/trunk
  patches:

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - xfab

about:
  license: GPL
  home: https://sourceforge.net/projects/fable/
  summary: Fable crystallography toolbox
