package:
  name: fabian
  version: trunk

source:
  svn_url: http://svn.code.sf.net/p/fable/code/fabian/trunk

requirements:
  build:
    - python
  run:
    - fabio
    - matplotlib
    - numpy
    - pillow
    - pmw
    - python
#   - pyopengl

test:
  imports:
    - Fabian

about:
  license: LGPL
  home: https://sourceforge.net/projects/fable/
  summary: 3D x-ray diffraction utilities
