package:
  name: fabio
  version: master

source:
  git_url: https://github.com/kif/fabio.git
  git_tag: master

requirements:
  build:
    - python
    - numpy
    - cython
    - pillow
  run:
    - python
    - numpy
    - pillow

test:
  imports:
    - fabio

about:
  license: LGPL
  home: https://github.com/kif/fabio
  summary: 3DXRD
