package:
  name: fabio
  version: 0.3.0

source:
  git_url: https://github.com/kif/fabio.git
  git_tag: v0.3.0

requirements:
  build:
    - python
    - numpy ==1.9.3
    - cython
    - pillow ==2.9.0
    - setuptools
  run:
    - python
    - numpy ==1.9.3
    - pillow ==2.9.0

test:
  imports:
    - fabio

about:
  license: GPL
  home: https://github.com/kif/fabio
  summary: Fable I/O library for diffraction images
