package:
  name: grainsweeper
  version: trunk

source:
  svn_url: http://svn.code.sf.net/p/fable/code/GrainSweeper

  patches:
    - edf_io.patch
    - gbmv_util.patch
    - Makefile.patch

#test:
#  commands:
#    - grainsweeper

about:
  license: LGPL
  home: https://sourceforge.net/projects/fable/
  summary: 3D x-ray diffraction utilities
