package:
  name: 3dxrd-scripts
  version: dev

requirements:
  build:
    - python
  run:
    - fabian
    - fabio
    - fitallb
    - grainspotter
    - grainsweeper3d
    - imaged11
    - python
    - scipy
    - sweep2png
    - tifffile
    - xfab

about:
  license: GPL
  home: https://sourceforge.net/projects/fable/
  summary: 3D x-ray diffraction utilities
