package:
  name: 3dxrd-scripts
  version: dev

requirements:
  run:
    - fabian
    - fabio
    - grainspotter
    - grainsweeper3d
    - imaged11
    - scipy
    - sweep2png
    - tifffile
    - xfab

#test:
#  commands:
#    - fumble

about:
  license: GPL
  home: https://sourceforge.net/projects/fable/
  summary: 3D x-ray diffraction utilities
